### PR TITLE
Few changes

### PR DESCRIPTION
**Pull request by michalmonday**
Hi, I noticed that the nested list in verb_list.py could be improved and accessed easier. Also, I wrote a comment on line 122 and 136 of hackergenerator.py about a small bug. 

I kept changing things but except the things mentioned above all the other changes are just cosmetic and mostly unnecessary.

Edit: 
```cpp
def main():
    n = 100 
```
Left this thing by accident... (in hackergenerator.py)

### CODE REVIEW

**Comment by spacehuhn** [comment]
Awaiting @GlOwl approval, my parts of the code are only improved thanks :)

**Comment by GlOwl** [comment]
Thanks, looked over it and there are a few good simplifications. 

for line 118 and 120 can you explain "[word for type_ , ... in type_]" to me? I'm a bit confused about it.

I just prefer for double quotes and for doc-strings its the convention recommends to use double quotes. https://www.python.org/dev/peps/pep-0257/
I think I will go with single quotes on flags and similar things and with double quotes on text that gets eventually printed.

**Comment by michalmonday** [comment]
Sorry about the quotes, I shouldn't change these.

About the line 118 and 120, the `ne` nested list contains the following pairs:
```python
ne=[
    ['smber', 'collector'], 
    ['smber', 'thread'], 
    ['smber', 'model'],
    ...
```

So this line: `[word for type_, word in ne if 's' in type_]` ...loops over the `ne` unpacking the pairs. For example the first iteration of the for loop will asign the following:
```python
type_ = "smber" 
word = "collector"
```
In other words:
`type_` substitutes `w[0]`
`word` substitutes `w[1]`

```python
random.choice([w for w in ne if "s" in w[0]])[1]

# is equivalent to:
random.choice([w[1] for w in ne if "s" in w[0]])

# which turns into:
random.choice([word for type_, word in ne if 's' in type_])
```

(I used `type_` as a variable name instead of `type` because `type()` is a built-in function)

This way the list comprehension returns the list of words like:
```
collector
thread
model
```
So there is no need to use `[1]` after `random.choice()`.

**Comment by spacehuhn** [comment]
bump

**Comment by GlOwl** [comment]
Looked over it again and decided that I will cherry-pick the good bits but can't merge because git doesn't let me pick which changes I want to add and which to leave out (especially now that we did a few other changes)

**Pull request closed without merging**
